version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    networks:
      - chat-network

  chat-service:
    build: .
    command: >
      sh -c "gunicorn --pythonpath /app chat.wsgi:application --bind 0.0.0.0:8000 &&  daphne -b 0.0.0.0 -p 8001 chat.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - chat-network
  krakend:
    image: devopsfaith/krakend
    container_name: krakend
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - "8081:8080" # KrakenD exposed on host:8081
    command: [ "run", "-dc", "/etc/krakend/krakend.json" ]
    depends_on:
      - chat-service
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongo_data:
