# Generated by Django 4.2.3 on 2025-03-21 12:28

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('custom_auth', 'Role')
    Role.objects.create(name="Startup")
    Role.objects.create(name="Investor")

class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]