# Generated by Django 4.2.3 on 2025-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0002_auto_20250321_1228"),
    ]

    operations = [
        migrations.CreateModel(
            name="KrakendPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("can_read", "Can Read"),
                            ("can_edit", "Can Edit"),
                            ("can_delete", "Can Delete"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleKrakendPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("NotValidated", "Not Validated"),
                            ("IsStartup", "Is Startup"),
                            ("IsInvestor", "Is Investor"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "krakendpermissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="custom_auth.krakendpermission",
                    ),
                ),
            ],
        ),
    ]
