# Generated by Django 4.2.3 on 2025-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0003_krakendpermission_rolekrakendpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermissionForKrakend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("NotValidated", "Not Validated"),
                            ("IsStartup", "Is Startup"),
                            ("IsInvestor", "Is Investor"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="custom_auth.krakendpermission",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RoleKrakendPermission",
        ),
    ]
