version: '3.8'

services:
    event-api:
      container_name: event_api
      build: ./Backend/event-service
      command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --reload'
      volumes:
        - ./BackEnd/event-service:/src
      ports:
        - ${EVENTS_HOST_PORT}:8000
      restart: always
      environment:
        - PYTHONPATH=/src/app 
      networks:
        - forum_network

volumes:
  profiles_data:


networks:
  forum_network:
    external: true