version: "3.8"

services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    volumes:
      - ./configs/postgres:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    networks:
      - forum_network
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DBS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    depends_on:
      - db
    networks:
      - forum_network

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - forum_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password

networks:
  forum_network:

volumes:
  db_data:
  pgadmin_data:
  mongo_data:
