"""participants_unique

Revision ID: d0da512d37fe
Revises: d48d1b3d083e
Create Date: 2025-03-23 23:15:01.241308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0da512d37fe"
down_revision: Union[str, None] = "d48d1b3d083e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_event_user_active",
        "event_participants",
        ["event_id", "user_id", "is_deleted"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_event_user_active", "event_participants", type_="unique"
    )
    # ### end Alembic commands ###
