"""participants update

Revision ID: d48d1b3d083e
Revises: 4ba79246f8e9
Create Date: 2025-03-23 12:27:53.515599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d48d1b3d083e"
down_revision: Union[str, None] = "4ba79246f8e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_participants",
        sa.Column("human_slots", sa.Integer(), nullable=False),
    )
    op.add_column(
        "event_participants",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "event_participants",
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "event_participants",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.drop_column("event_participants", "slots")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_participants",
        sa.Column("slots", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("event_participants", "updated_at")
    op.drop_column("event_participants", "created_at")
    op.drop_column("event_participants", "is_deleted")
    op.drop_column("event_participants", "human_slots")
    # ### end Alembic commands ###
