basePath: /
info:
  contact: {}
  description: This service provides validation JWT-token
  title: Authorization Service API
  version: "1.0"
paths:
  /check:
    get:
      consumes:
      - application/json
      description: Retrieves a JWT token from the Authorization header and optionally
        checks the user's role.
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Role to check
        enum:
        - Public
        - NotValidated
        - IsActive
        - IsStartup
        - IsInvestor
        in: query
        name: requiredRole
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'User role: <roleClaim>'
          schema:
            type: string
        "401":
          description: Missing Authorization header or invalid/expired token
          schema:
            type: string
        "403":
          description: Forbidden for this role
          schema:
            type: string
      summary: JWT validation
      tags:
      - auth
swagger: "2.0"
