version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  auth_service:
    build: .
    container_name: auth_service
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/home/authentication/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  auth_postgres_data:
