services:
  authentication_postgres:
    image: postgres:15
    container_name: authentication_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - forum_network

  authentication_service:
    build: .
    container_name: authentication_service
    restart: on-failure
    depends_on:
      - authentication_postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/home/authentication/app
    command: ["sh", "./start.sh"]
    networks:
      - forum_network


volumes:
  auth_postgres_data:

networks:
  forum_network:
    external: true
