version: '3.9'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krakend_gateway
    ports:
      - "8080:8080"
    command: [ "run", "-c", "krakend.json" ]
    networks:
      - forum_network

networks:
  forum_network:
    driver: bridge