# Generated by Django 4.2.3 on 2025-03-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0004_moderationemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoapprovetask",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
