FROM mongo:5

RUN apt-get update && apt-get install -y openssl && \
    openssl rand -base64 756 > /etc/mongo-keyfile && \
    chmod 600 /etc/mongo-keyfile && \
    chown mongodb:mongodb /etc/mongo-keyfile && \
    apt-get remove -y openssl && apt-get autoremove -y && apt-get clean

CMD ["mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]
