"""added banner field to startup profile model

Revision ID: 036965f74f2f
Revises: 4329280dbdbd
Create Date: 2025-03-25 21:32:13.455717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036965f74f2f'
down_revision: Union[str, None] = '4329280dbdbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startup_profiles', sa.Column('banner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'startup_profiles', 'profile_images', ['banner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'startup_profiles', type_='foreignkey')
    op.drop_column('startup_profiles', 'banner_id')
    # ### end Alembic commands ###
