"""empty message

Revision ID: 1cef0534e5e8
Revises: ce8278b94e79
Create Date: 2025-04-03 13:20:32.873934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cef0534e5e8'
down_revision: Union[str, None] = 'ce8278b94e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rnokkpp_valid', sa.Boolean(), nullable=False),
    sa.Column('edrpou_valid', sa.Boolean(), nullable=False),
    sa.Column('last_validation_request_uuid', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['startup_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_validations')
    # ### end Alembic commands ###
