"""adding migrations at once

Revision ID: 2e165bcb7d91
Revises: c321338fac1c
Create Date: 2025-02-26 23:42:09.621051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e165bcb7d91'
down_revision: Union[str, None] = 'c321338fac1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UNDEFINED', 'PENDING', 'BLOCKED', 'APPROVED', 'AUTOAPPROVED', name='statusenum'), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('is_startup', sa.Boolean(), nullable=False),
    sa.Column('is_fop', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('category')
    # ### end Alembic commands ###
