"""removed created_by field

Revision ID: 4329280dbdbd
Revises: 8602d804c324
Create Date: 2025-03-25 20:24:09.497078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4329280dbdbd'
down_revision: Union[str, None] = '8602d804c324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_images_created_by_fkey', 'profile_images', type_='foreignkey')
    op.drop_column('profile_images', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_images', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('profile_images_created_by_fkey', 'profile_images', 'startup_profiles', ['created_by'], ['id'])
    # ### end Alembic commands ###
