"""empty message

Revision ID: 58b83a66082a
Revises: 63d6f7ab80f9
Create Date: 2025-03-12 20:29:13.709574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b83a66082a'
down_revision: Union[str, None] = '63d6f7ab80f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone', sa.String(length=12)))
    op.add_column('profiles', sa.Column('edrpou', sa.String(length=10)))
    op.add_column('profiles', sa.Column('rnokpp', sa.String(length=10)))
    op.add_column('profiles', sa.Column('founded', sa.Integer()))
    op.add_column('profiles', sa.Column('startup_idea', sa.String(length=10)))
    op.add_column('profiles', sa.Column('created_at', sa.DateTime()))
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=sa.func.now()))
    op.create_unique_constraint("uq_profiles_rnokpp", "profiles", ["rnokpp"])
    op.create_unique_constraint("uq_profiles_edrpou", "profiles", ["edrpou"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_profiles_rnokpp", 'profiles', type_='unique')
    op.drop_constraint("uq_profiles_edrpou", 'profiles', type_='unique')
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'created_at')
    op.drop_column('profiles', 'startup_idea')
    op.drop_column('profiles', 'founded')
    op.drop_column('profiles', 'rnokpp')
    op.drop_column('profiles', 'edrpou')
    op.drop_column('profiles', 'phone')
    # ### end Alembic commands ###
