"""added images table

Revision ID: 8602d804c324
Revises: 927220397b35
Create Date: 2025-03-25 16:48:29.529297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8602d804c324'
down_revision: Union[str, None] = '927220397b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


image_type_enum = sa.Enum(
    'BANNER', 
    'LOGO',
    name='statusenum').with_variant(
    postgresql.ENUM(
        'BANNER', 
        'LOGO',
        name="imagetypeenum",
        create_type=False,
    ),
    "postgresql",
)



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('image_type', image_type_enum, nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False, default=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['startup_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_images')
    # ### end Alembic commands ###
