"""many to many using classes

Revision ID: 90bf2adcf533
Revises: 04340309a9c8
Create Date: 2025-02-27 14:27:37.583545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bf2adcf533'
down_revision: Union[str, None] = '04340309a9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_category', sa.Column('dummy_field', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_category', 'dummy_field')
    # ### end Alembic commands ###
