"""added investor model

Revision ID: 927220397b35
Revises: de52215cf1a8
Create Date: 2025-03-18 15:34:56.158399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.startups import StatusEnum
from sqlalchemy.dialects import postgresql



status_enum = sa.Enum(
    'UNDEFINED', 'PENDING', 'BLOCKED', 'APPROVED', 'AUTOAPPROVED', 
    name='statusenum').with_variant(
    postgresql.ENUM(
        'UNDEFINED', 
        'PENDING', 
        'BLOCKED', 
        'APPROVED', 
        'AUTOAPPROVED',
        name="statusenum",
        create_type=False,
    ),
    "postgresql",
)




# revision identifiers, used by Alembic.
revision: str = '927220397b35'
down_revision: Union[str, None] = 'de52215cf1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('is_legal_entity', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('edrpou', sa.String(length=8), nullable=True),
    sa.Column('rnokpp', sa.String(length=10), nullable=True),
    sa.Column('available_funds', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=sa.func.now()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edrpou'),
    sa.UniqueConstraint('rnokpp')
    )
    op.create_table('investor_startup_categories',
    sa.Column('investor_profile_id', sa.Integer(), nullable=False),
    sa.Column('startup_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_profile_id'], ['investor_profiles.id'], ),
    sa.ForeignKeyConstraint(['startup_category_id'], ['startup_category.id'], ),
    sa.PrimaryKeyConstraint('investor_profile_id', 'startup_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investor_startup_categories')
    op.drop_table('investor_profiles')
    # ### end Alembic commands ###
