"""added reverse fk

Revision ID: 9f6df98d2035
Revises: fe4d078b45d4
Create Date: 2025-03-25 23:29:26.207480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6df98d2035'
down_revision: Union[str, None] = 'fe4d078b45d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_images', sa.Column('profile_banner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile_images', 'startup_profiles', ['profile_banner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_images', type_='foreignkey')
    op.drop_column('profile_images', 'profile_banner_id')
    # ### end Alembic commands ###
