"""empty message

Revision ID: 9fd1802010e6
Revises: 1cef0534e5e8
Create Date: 2025-04-04 20:28:40.745904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd1802010e6'
down_revision: Union[str, None] = '1cef0534e5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investor_profiles', sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('startup_profiles', sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('startup_profiles', 'user_id')
    op.drop_column('investor_profiles', 'user_id')
    # ### end Alembic commands ###
