"""added realtions between categories and profile models

Revision ID: a389ab99da0b
Revises: 138eedcefc18
Create Date: 2025-02-27 09:34:53.470728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a389ab99da0b'
down_revision: Union[str, None] = '138eedcefc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profiles', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'category_id')
    # ### end Alembic commands ###
