"""empty message

Revision ID: b8cf15fa8a08
Revises: 4192e6d67b3d
Create Date: 2025-03-16 21:54:53.297758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8cf15fa8a08'
down_revision: Union[str, None] = '4192e6d67b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('startup_profiles', 'phone',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('startup_profiles', 'edrpou',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=True)
    op.alter_column('startup_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('startup_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('startup_profiles', 'edrpou',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('startup_profiles', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
