"""implemented many to many

Revision ID: c4c6338574fd
Revises: a389ab99da0b
Create Date: 2025-02-27 11:51:02.038315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c6338574fd'
down_revision: Union[str, None] = 'a389ab99da0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_category',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'category_id')
    )
    op.drop_constraint('profiles_category_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('profiles_category_id_fkey', 'profiles', 'category', ['category_id'], ['id'])
    op.drop_table('profile_category')
    # ### end Alembic commands ###
