"""empty message

Revision ID: ce8278b94e79
Revises: 9f6df98d2035
Create Date: 2025-03-27 13:50:24.740620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8278b94e79'
down_revision: Union[str, None] = '9f6df98d2035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_images_profile_banner_id_fkey', 'profile_images', type_='foreignkey')
    op.drop_column('profile_images', 'profile_banner_id')
    op.drop_constraint('uq_profiles_edrpou', 'startup_profiles', type_='unique')
    op.drop_constraint('uq_profiles_rnokpp', 'startup_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_profiles_rnokpp', 'startup_profiles', ['rnokpp'])
    op.create_unique_constraint('uq_profiles_edrpou', 'startup_profiles', ['edrpou'])
    op.add_column('profile_images', sa.Column('profile_banner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profile_images_profile_banner_id_fkey', 'profile_images', 'startup_profiles', ['profile_banner_id'], ['id'])
    # ### end Alembic commands ###
