"""empty message

Revision ID: f00f18d00977
Revises: b8cf15fa8a08
Create Date: 2025-03-18 11:03:28.163178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00f18d00977'
down_revision: Union[str, None] = 'b8cf15fa8a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starup_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('starup_profile_category',
    sa.Column('startup_profile_id', sa.Integer(), nullable=False),
    sa.Column('startup_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['startup_category_id'], ['starup_category.id'], ),
    sa.ForeignKeyConstraint(['startup_profile_id'], ['startup_profiles.id'], ),
    sa.PrimaryKeyConstraint('startup_profile_id', 'startup_category_id')
    )
    op.drop_table('profile_category')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    sa.UniqueConstraint('name', name='category_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('profile_category',
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='profile_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['profile_id'], ['startup_profiles.id'], name='profile_category_profile_id_fkey'),
    sa.PrimaryKeyConstraint('profile_id', 'category_id', name='profile_category_pkey')
    )
    op.drop_table('starup_profile_category')
    op.drop_table('starup_category')
    # ### end Alembic commands ###
