"""removed image_type

Revision ID: fe4d078b45d4
Revises: 036965f74f2f
Create Date: 2025-03-25 22:16:11.220578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe4d078b45d4'
down_revision: Union[str, None] = '036965f74f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_images', 'image_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_images', sa.Column('image_type', postgresql.ENUM('BANNER', 'LOGO', name='imagetypeenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
