services:
  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: ${REDIS_HOSTS}